---
title: "03.sdm_convol"
author: "Guillaume Papuga"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, include=FALSE, message=FALSE, warning=FALSE)
```

```{r packages}
library (tidyverse)
library (ade4)
library (here)
library (stringr)
library (ade4)
library (dismo)
library (mapdata)
library (maps)
library (maptools)
library (raster)
library (rgdal)
library (rgeos)
library (sdm)
library (sp)
library (usdm) 
```



```{r}
### Définir la zone d'étude et en faire un objet "Spatial Polygon"
### Define the projection of the project 
p.proj = "+proj=longlat +datum=WGS84"

# with an online database
zone.etude <-map("world", regions="Italy:Sardinia", exact=F, fill=T)  # défini le fond de carte en "objet map"; il faut que "fill = T" pour pouvoir convertir en spatialpolygon
IDs <- sapply(strsplit(zone.etude$names, ":"), function(x) x[1]) # récupère les noms des pays
zone.etudeSpp <- map2SpatialPolygons(zone.etude, IDs=IDs, proj4string=CRS(p.proj))  # convertit en "Spatial Polygon"

# with a polygon of the project
# zone.etudeSpp <- readOGR('bound.shp') 
# proj4string(zone.etudeSpp)
# zone.etudeSpp <- spTransform(bnd,CRSobj = CRS(proj4string(sp))) # convert the CRS for the same projection

# based on the presence points * a radius

### Define the global extent of the project
e = extent(zone.etudeSpp) # recuperer spatial extent du shapefile utilisé pour extraire les données
e = drawExtent(show=TRUE, col="red") # draw the spatial extent


###############################################################################################
######################### Méthode simple : GLM ################################################
###############################################################################################

#------------------------------------------------------------------------
# Pre processing
#-----------------------------------------------------------------------
### 1. Environmental data
# 1b. Download data from internet
bioclim.data = getData('worldclim', var='bio', res=0.5, lon = 8, lat = 40) # from raster package
predictors = crop (bioclim.data, e)
r = predictors

# each time you want to stack data, you have to respect the same PROJECTION - EXTENT - RESOLUTION

### 2. Presence data
# 2a. Gather presence data
# Upload data from your computer
sp = read.csv("cyc.sard.loc.csv", header = T, row.names = 1, sep = ";", dec = ",") # CSV file

# to transform a matrix file to a spatial point file
coordinates (sp) = ~x*y # the name of the x and y columns
proj4string (sp) = p.proj # attributes a projection for the object, it DOES NOT reproject
sp1 = sp[which(sp$status == "p"),] # keep only the presence
sp1$species = 1
sp1 = sp1[,"species"]

### 5. Variables selection
# PCA
df = as.data.frame(r)
df = na.omit(df)
pca = dudi.pca (df, scannf = F, nf = 2)
s.corcircle (pca$co, clabel = 0.6)

# var.r = c("bio1_16", "bio3_16", "bio15_16", "bio7_16", "bio12_16")
r1 = stack(r$bio1_16, r$bio2_16)

#------------------------------------------------------------------------
# Processing
#------------------------------------------------------------------------

### Step 1. Create a loop to select which model should be used

mat.auc = as.data.frame(matrix(data = NA, ncol = 1, nrow = 275))
colnames(mat.auc)[1] = 'mod.id'
mat.auc$mod.id = 1:275

mat.tss = as.data.frame(matrix(data = NA, ncol = 1, nrow = 275))
colnames(mat.tss)[1] = 'mod.id'
mat.tss$mod.id = 1:275

for (i in 1:50){
  ### create the sdmData object with spatial data
  d = sdmData (species ~ ., train = sp1, predictors = r1, 
               bg = list(n = 44, method = 'gRandom', remove = T))
  
  ### fit the model
  m = sdm (species ~., data = d, 
           methods = c('bioclim', 'brt', 'cart', 'domain.dismo', 'fda', 'gam', 'glm', 'mars', 'mda', 'rf', 'svm'), # algorithms
           replication = 'cross-validation', # method
           cv.folds = 5,
           n = 5, 
           modelSettings = list (brt = list (n.trees = 2000, shrinkage = 0.01))) # change the default settings of each model
  
  ### Extract both values and store them into a dataframe
  m.auc = getEvaluation(m, stat='AUC')
  mat.auc = merge (mat.auc, m.auc, by.x = 'mod.id', by.y = 'modelID', all.x = T)
  
  m.tss = getEvaluation(m, stat='TSS')
  mat.tss = merge (mat.tss, m.tss, by.x = 'mod.id', by.y = 'modelID', all.x = T)
  }

mod.info = getModelInfo(m)

### Model selection
## AUC
# matrix
colnames(mat.auc) = c('mod.id', 1:50)
mat.test.auc = cbind(as.data.frame(mod.info[,'method']), mat.auc[,-1])
colnames(mat.test.auc)[1] = 'model'
mean.auc = aggregate(.~ model, data = mat.test.auc, FUN = 'mean')
row.names(mean.auc) = mean.auc$model
mean.auc = t(mean.auc[,-1])
mean.auc

# sort the matrix
vec.sort = colMeans(mean.auc)
mat.sort.auc = mean.auc[,order(vec.sort)]

# plot
boxplot(mat.sort.auc) 
abline(h = 0.7, col = "red")

## TSS
# matrix
colnames(mat.tss) = c('mod.id', 1:50)
mat.test.tss = cbind(as.data.frame(mod.info[,'method']), mat.tss[,-1])
colnames(mat.test.tss)[1] = 'model'
mean.tss = aggregate(.~ model, data = mat.test.tss, FUN = 'mean')
row.names(mean.tss) = mean.tss$model
mean.tss = t(mean.tss[,-1])
mean.tss

# sort the matrix
vec.sort.t = colMeans(mean.tss)
mat.sort.tss = mean.tss[,order(vec.sort.t)]

# plot
boxplot(mat.sort.tss) 
abline(h = 0.5, col = "red")


### Step 2. Create the model with fda, glm, gam, mda
### Empty stack
stk = stack()

eval = as.data.frame(matrix(data = NA, ncol = 1, nrow = 50))
colnames(eval)[1] = 'auc'

### loop to generate 50 replicates of the model
for (i in 1:50){
  # create the sdmData object with spatial data
  d = sdmData (species ~ ., train = sp1, predictors = r1, 
               bg = list(n = 44, method = 'gRandom', remove = T))
  
  # fit the models
  m = sdm (species ~., data = d, 
           methods = c( 'fda', 'gam', 'glm', 'mda'), # algorithms
           replication = 'cross-validation', # method
           cv.folds = 5,
           n = 5) 
  
  # Run an ensemble model with all models
  setwd("~/Dropbox/Recherche/Projets & articles/en cours/article_Cyclamen in Sardinia/data/SDM/raster.ensemble")
  en = ensemble(m, r1, filename = paste ('ens', i, '_sdm.img', sep = ''),
                setting=list(method='weighted', stat='AUC', opt=2))
  
  # evaluate the model
  tab.eval = as.data.frame(cbind(coordinates(d), as.data.frame(d)$species))
  tab.eval = cbind(tab.eval, extract(en, tab.eval[,c('x', 'y')]))
  colnames(tab.eval)[3:4] = c('species', 'suitability')
  
  val.auc = evaluates(tab.eval$species, tab.eval$suitability)
  eval[i,'auc'] = val.auc@statistics$AUC
  
  # create the stack
  stk = addLayer(stk, en)
  
  # set the right directory back again
  setwd("~/Dropbox/Recherche/Projets & articles/en cours/article_Cyclamen in Sardinia/data/SDM")
}

### Step 3. create the two raster layers (mean + std error)  
# Mean prediction
m.pred = calc(stk, mean)

# map Sardinia
map.it = raster::getData('GADM', country='ITA', level = 1)
sard = map.it[map.it$NAME_1 == "Sardegna",]
plot(sard, bg="white", axes=T, col = "white", lwd = 3)

# add the suitability map
m.pred.sard = mask (m.pred, sard)
plot(m.pred.sard, main='weighted mean of three models', box = F, add = T)

# add the dots
#gbif.cycl = read.csv("gbif.database.csv",header=TRUE,row.names=NULL,dec=".",sep=";")
#points(gbif.cycl$x, gbif.cycl$y, 
#       pch = 16, cex = 0.4, col = 'black')
points(sp1, pch = 16, cex = 0.6, col = 'red')
points(sp[which(sp$status == 'm'),], pch = 16, cex = 0.6, col = 'blue')


# Plot AUC
hist(eval$auc, freq = T)

# Standard error
se.pred = calc(stk,function(x) sd(x)/sqrt(length(x)))
plot(sard, bg="white", axes=T, col = "white", lwd = 3)
# add the standard error map
se.pred.sard = mask (se.pred, sard)
plot(se.pred.sard, box = F, add = T)

plot(se.pred)

# Evaluation
mean(eval$auc)
sd(eval$auc)/sqrt(length(eval$auc))


### Step 4. Produce individual maps for fda, glm, gam, mda
### Empty stack
stk = stack()

for (i in 1:50){
  # create the sdmData object with spatial data
  d = sdmData (species ~ ., train = sp1, predictors = r1, 
               bg = list(n = 44, method = 'gRandom', remove = T))
  
  # fit the models c( 'fda', 'gam', 'glm', 'mda')
  m = sdm (species ~., data = d, 
           methods = 'mda', # algorithms
           replication = 'cross-validation', # method
           cv.folds = 5,
           n = 5) 
  
  # Run an ensemble model with all models
  setwd("~/Dropbox/Recherche/Projets & articles/en cours/article_Cyclamen in Sardinia/data/SDM/raster.ensemble")
  en = ensemble(m, r1, filename = paste ('ens.mda', i, '_sdm.img', sep = ''),
                setting=list(method='weighted', stat='AUC', opt=2))
  
    # create the stack
  stk = addLayer(stk, en)
  
  # set the right directory back again
  setwd("~/Dropbox/Recherche/Projets & articles/en cours/article_Cyclamen in Sardinia/data/SDM")
}

### Step 5. create the two raster layers (mean + std error)  
# Mean prediction
m.pred = calc(stk, mean)

# map Sardinia
# map.it = raster::getData('GADM', country='ITA', level = 1)
# sard = map.it[map.it$NAME_1 == "Sardegna",]
plot(sard, bg="white", axes=T, col = "white", lwd = 3, main = 'MDA')

# add the suitability map
m.pred.sard = mask (m.pred, sard)
plot(m.pred.sard, box = F, add = T)



### evaluate models
m
getModelInfo(m)
gui(m) # open the interface 
roc(m)
getRoc(m2)
getVarImp (m,2)
rcurve(m, id = 1) # plot the response curve
getResponseCurve (m, 1)



### Run an ensemble model with all models
en3 <- ensemble(m, r3, filename='ensemble3_sdm.img',
               setting=list(method='weighted', stat='TSS', opt=2))
en4 <- ensemble(m2, r3, filename='ensemble4_sdm.img',
                setting=list(method='weighted', stat='TSS', opt=2))


### Select a subset of models with a given threshold
# which models have TSS >= 0.7
ev <- getEvaluation(m,stat='TSS',opt = 2)
ev
id <- ev$modelID[which(ev$TSS >= 0.7)] 
# we run ensemble by incorporating the models with TSS >= 0.6:
en3 <- ensemble(m, r3, filename='ensemble3_sdm.img',
                setting=list(id=id, method='weighted', stat='TSS', opt=2))



# we can take the mean of raster over different runs for each method and species:
pm = predict(m, newdata = r3, filename='pm.img', mean=T, overwrite = T)
plot(pm)
plot(en)



# Set a working directory
setwd("~/Dropbox/Recherche/Projets & articles/en cours/article_Cyclamen in Sardinia/data/SDM/raster.ensemble")
lst <- list.files(pattern = '^ens(.*)img$')
lst = lst [201:250]
stk <- stack(lst)

std.error <- function(x) {
  se <- sd(x)/sqrt(length(x))
  return(se)
}
se.preds = calc(stk, std.error)
se.preds.sard = mask (se.preds, sard)
plot(se.preds.sard, box = F, add = T)

```

